# ----------------------- #
#      User Configs       #
# ----------------------- #

name: Renata Carreira
title: "Desenvolvedora, Carioca"
gravatar_email: 
# don't forget to edit your "about" on _includes/about.md
# for more information about markdown, consider giving a look at some examples and basics in the follow urls:
# http://daringfireball.net/projects/markdown/basics
# http://en.wikipedia.org/wiki/Markdown


# ----------------------- #
#       Info Configs      #
# ----------------------- #

info:
  location: Rio de Janeiro
  code: Python, Django # Programmer? Put your programming languages and technologies here
  company: Globosat
  university: Estácio de Sá - Análise de Sistemas
  interests: Desenvolvimento Web, Open Source, HQs, Videogames, Pizza, RPG, Café (descafeinado)
  email: contato@renatacarreira.com

# ----------------------- #
#      Social Configs     #
# ----------------------- #

# Put your usernames here. Only usernames, without links.

social:
# Note about github: write down your_username/your_repository if you want to show a repository page, instead of your github account.
  github: recarreira
  linkedin: renatacarreira
  facebook: re.carreira
  twitter: Renata_Carreira
  foursquare:
  goodreads:
# Note about google+: Your googleplus username should be that huge number in your url (example: for https://plus.google.com/u/1/112176414644635750645/posts, your username is 112176414644635750645).
# For google+ pages, you may find this huge number written down 2 times. We only need it once.
  googleplus: 108053960108837767753
  lastfm: recarreira
  grooveshark: recarreira
  rdio: RenataCarreira
  instagram: recarreira
  flickr: recarreira
  quora:
  stackoverflow:
  rss:


# Now you should put your links.

links:
  -
    title: "Dev - Blog sobre Desenvolvimento"
    url: "http://dev.renatacarreira.com/"
  -
    title: "[Off Topic] - Blog para as horas vagas"
    url: "http://offtopic.renatacarreira.com"
  -
    title: "Learn How to Code"
    url: "http://learnhowtocode.in/"
  -
    title: "All About You - demo"
    url: "http://renatacarreira.com/all_about_you/"


# ----------------------- #
#      Project Configs    #
# ----------------------- #

# Google Analytics
google_analytics_tracking_id: UA-42001979-1

# Only make changes here if you _realy_ know what you're doing. Just an advice.

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']
